dist: trusty
sudo: false

branches:
  only:
    - master

env:
  - TF_INPUT=false

# Install terraform
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

script: terraform init

deploy:
- provider: script
  skip_cleanup: true
  script: terraform plan
  on:
    branch: master
