#Install a Terraform executable
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_windows_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

#These two steps will effectively validate our terraform and output a list of any changes to be made to our infrastructure
script: terraform init ./terraform
